### ISSUE TITLE
<dl id=...> a few id typos

### ISSUE THREAD

**Issue by anotatta** [suttacentral/sc-data#107]
Perhaps a few error on file pli2en_pts.json on tag <dl id=...>

Line 9027	panunna (Paṇunn  should be panunna
Line 9028	panuṇṇa)  should be paṇunna
Line 9029	panunna (Paṇunna should be panuṇṇa

The following three are repeat of the previous three.
Line 9030	panuṇṇa)
Line 9031	panunna (Paṇunna
Line 9032	panuṇṇa)

Line 10824	brāhmañña. brāhmaññatā should be brāhmañña

**Comment by sujato** [comment]
Thanks, I have fixed these.
