### ISSUE TITLE
Where to find po files in the outdated directory: sc-data/po_text/pli-en

### ISSUE THREAD

**Issue by bksubhuti** [suttacentral/sc-data#111]
I'm looking to find what was once located at:
suttacentral/sc-data/po_text/pli-en
Files are in .po extensions.

These above files were used to download and compile epubs for the 6 nikayas translated by Ajahn Sujato.
I'm looking to find that in the Vinaya which is newly translated that contains both the pali/english.

There is a plan to integrate these files into a main reader for Tipitaka Pali projector and / or Tipitaka Pali Reader or something else, plus parsing and making new epubs.

**Comment by sujato** [comment]
PO files are deprecated, and the Vinaya translation doesn't exist in PO, not in full version anyway. All the PO files are out of date. Don't use them.

Use the latest published branch of bilara-data JSON files for all our translations.

https://github.com/suttacentral/bilara-data

Use bilara i/o to extract the translations you want into a spreadsheet, then use that for making EPUBs.

Note that Q1 2022 our plan is to add export of translations in multiple formats, including EPUB:

https://github.com/suttacentral/suttacentral/projects/6

So if you can wait a few months, that should be available. Meanwhile, if you have any suggestions, please note them in the publications project above.

**Comment by bksubhuti** [comment]
I don't understand bilara and how to use it.
"Wait just a few months"... and not have to do anything.. **surely, I can wait a few months.**

**Outdated:**
Please look at https://americanmonk.org/wp-content/uploads/2020/06/epub.zip
These were processed and made by Ven DhammaNyana
I use these books often on my eReader and look up certain words in question on TPP.

We hope to include this in TPP and perhaps TPR soon with integration into the main reader view.
There are also hopes to make an English Flutter SQLite FTS app for all "free" english works available.

Perhaps there can be some collab on your team for giving us certain data formats when that happens.

**Comment by bksubhuti** [comment]
current english only sc-vinaya book is a little big.  searchable yes.. but big.  Maybe break up into proper volumes.

**Comment by sujato** [comment]
All our data is in JSON format, it is easily extracted and turned into whatever form you need. Bilara i/o is a simple utility for working with our data. If you have the capacity to build apps, you most definitely have the capacity to deal with Bilara JSON.

>I don't understand bilara and how to use it.

It is explained in the link I supplied earlier. 

https://github.com/suttacentral/bilara-data

**Comment by bksubhuti** [comment]
I simply don't know where to find the files.  IF it is as easy as you say.. the docs do not reference the files.
It says the files are in root.. but I don't understand WHERE to find the files.

Please update the example that lists the exact locations of these json files.  Exploring git in web is not easy.
So when I do so.. it is something "I do not understand"

**Comment by bksubhuti** [comment]
I downloaded bilara and I was able to understand things better with visual code.
This is not so difficult to work with .  However, it would be good if you updated the doc.
To reflect the full path.  In this way it is discoverable within the github web interface.

for the MN1 example.
```
translation/en/sujato/sutta/mn/mn1_translation-en-sujato.json
root/pli/ms/sutta/mn/mn1_root-pli-ms.json

```
