### ISSUE TITLE
*cittavipariyesa* in the ncped dictionary file

### ISSUE THREAD

**Issue by buddhist-uni** [suttacentral/sc-data#118]
There's some confused thinking in the `pli2en_ncped.json` file.  The entry for *cittavipariyesa* on line 56248 is in a different format than every other entry.  Is this a joke??

**Comment by sujato** [comment]
Thanks, I've fixed it.

https://github.com/suttacentral/sc-data/commit/47700942f01217741232ba541e10df7dd8a40894
