### ISSUE TITLE
Where or how to get suttanta and vinaya in Thai script at suttacentral github?

### ISSUE THREAD

**Issue by o28o** [suttacentral/sc-data#185]
Good day. 

I wanted to check the thai script tipitaka in sc data files. But seems there are no files like .json or html 

Except translations in ./html_text/th

How can I get the Root texts in Thai script?

**Comment by thesunshade** [comment]
That's probably a better question to ask on the SC forum. 

I believe that all of the texts in non-roman alphabets are created using the technology of http://aksharamukha.appspot.com/converter

If you are actually looking for the Thai manuscript, then that's not on SC at all. I believe that the Digital Pali Reader has it, though.

**Comment by o28o** [comment]
Thank you. I'll check dpr and aksharamukha

**Comment by sujato** [comment]
Yes, just to confirm, on SC our Pali texts are purely in roman script, and converted to other scripts with the *incredible* aksharamukha. There are some databases that have the Thai editions, but I can't say how accurate they are.

**Comment by o28o** [comment]
Hi there
How are you?
I finally made the local copy based sc light. It even emulates api with next and prev suttas.
https://find.dhamma.gift/scm/?q=sn56.11&lang=pli
I wanted to move next and prev sutta buttons to the top of the page but I don't understand what is that))))
Looks like this part is responsible for the button location. How you generate buttons like this? I don't even know how to Google such thing😊😊😊
        ? `<a href="?q=${nextSlug}&lang=${language}">${nextSlugPrint} ${nextName}<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" id="body_1" width="15" height="11"> 

      <g transform="matrix(0.021484375 0 0 0.021484375 2 -0)"> 
        <g> 
              <path d="M202.1 450C 196.03278 449.9987 190.56381 446.34256 188.24348 440.73654C 185.92316 435.13055 187.20845 428.67883 191.5 424.39L191.5 424.39L365.79 250.1L191.5 75.81C 185.81535 69.92433 185.89662 60.568687 191.68266 54.782654C 197.46869 48.996624 206.82434 48.91536 212.71 54.6L212.71 54.6L397.61 239.5C 403.4657 245.3575 403.4657 254.8525 397.61 260.71L397.61 260.71L212.70999 445.61C 209.89557 448.4226 206.07895 450.0018 202.1 450z" stroke="none" fill="#8f8f8f" fill-rule="nonzero" /> 
        </g> 
      </g> 
      </svg></a>` 
        : ""; 
    }
--

BR
Pavel K
https://find.dhamma.gift - Liberation Search Engine. Поисковая Система Освобождения  Thursday, 29 December 2022, 09:13AM +07:00 from thesunshade  ***@***.*** :

**Comment by thesunshade** [comment]
Now, this would be a better thing to ask on the sc-mini repository. :-) Could paste it into an issue there? And maybe close this issue?

**Comment by o28o** [comment]
Oops sorry. Didn't know that you are in SC data aswell)
--

BR
Pavel K
https://find.dhamma.gift - Liberation Search Engine. Поисковая Система Освобождения  Saturday, 28 January 2023, 10:10AM +07:00 from thesunshade  ***@***.*** :
