### ISSUE TITLE
Leading 0 in filenames would be helpful

### ISSUE THREAD

**Issue by 153** [suttacentral/sc-data#192]
I see that in several directories, eg [html_text/en/pli/sutta/sn](https://github.com/suttacentral/sc-data/tree/master/html_text/en/pli/sutta/sn), the file naming convention goes `[1, 2, 3, ... 9, 10, 11...]` 

Leading 0s for suttas, eg `[001, 002, 003 ... 009, 010, 011]` would make the directories be sorted properly in directory indices. I'm not sure that any collection of texts has more than 999 suttas so 3 digit naming conventions ought to suffice. 

This is only a minor stylistic issue. It would likely be easy to bulk-rename directories through automation, but it may break things -- I don't know how the code works.

**Comment by sujato** [comment]
Thanks for the suggestion, but I think we'll keep things as they are.

**Comment by thesunshade** [comment]
I'm also happy to see this stay the way it is. If I could turn back time, it might have been nice to have from the beginning. But it could break a lot now without any big benefit.
