### ISSUE TITLE
Typo in dn34, 8.29, dn 34

### ISSUE THREAD

**Issue by o28o** [suttacentral/sc-data#193]
Hi. 

There is a typo in Dn33 also in an8.29, dn34

Puna caparaṁ, āvuso, tathāgato ca loke **na** uppanno hoti arahaṁ sammāsambuddho,

Furthermore, a Realized One has arisen in the world. - but should be negative.

**Comment by thesunshade** [comment]
Just an FYI, there is a thread on the discussion forum for reporting typos: https://discourse.suttacentral.net/t/bring-the-happiness-that-most-people-only-dream-about-tell-us-our-mistakes/26960
