### ISSUE TITLE
In the /html_text/de/pli/sutta/sn/sn11 directory, there seems to be redundant data.

### ISSUE THREAD

**Issue by ihongda** [suttacentral/sc-data#218]
The files in this directory seem to be duplicated with the files in html_text/de/pli/sutta/sn. Do these files have other uses?

These files currently cause errors loading data into the database.

![截图 2023-05-29 20-59-49](https://github.com/suttacentral/sc-data/assets/4037966/f07204ae-dd1a-4862-b248-2d197ab1bc14)

**Comment by ayya-vimala** [comment]
Thank you for spotting this error and my apologies for not checking more thoroughly before uploading. I've removed this now and created a new pull request: https://github.com/suttacentral/sc-data/pull/220
(In short: just remove all the folders inside SN11 and keep files sn11.1-sn11.25)
