### ISSUE TITLE
Indonesian sutta titles truncated

### ISSUE THREAD

**Issue by ccronje** [suttacentral/sc-data#225]
Discussion continued from https://github.com/suttacentral/bilara-data/issues/2648
Reported by @renaldoaluska

Some sutta titles are truncated:

![image](https://github.com/suttacentral/sc-data/assets/7553548/d7b7093a-418e-4b71-b4ab-3c747a26e556)
![image](https://github.com/suttacentral/sc-data/assets/7553548/38269100-c5bc-48a6-8ebe-63715245e7e7)

In mn29, the title is supposed to be "Khotbah panjang tentang Perumpamaan Inti Kayu" but the "Perumpamaan Inti Kayu" part is in the text instead of the title.

This kind of issue also applies to mn37, mn38, mn62, mn63, mn64, mn147.

@ihongda found that:
The title is taken from the `h1` tag in the html file - to fix it the source file needs to be edited:
https://github.com/suttacentral/sc-data/blob/master/html_text/id/pli/sutta/mn/mn29.html

Bhante @sujato can you please advise on next steps?

**Comment by renaldoaluska** [comment]
Update: also mn132, mn134, mn135.
"Ānanda dan" is "Ānanda and" in English, the title should've been "Ānanda and One Fine Night" that is "Ānanda dan
Satu Malam Yang Baik“.

<img width="952" alt="image" src="https://github.com/suttacentral/sc-data/assets/21968935/0eb5906d-e8d4-440f-ab84-7335743a7092">

Here is the [link to DhammaCitta's MN page](https://dhammacitta.org/teks/mn.html).
