### ISSUE TITLE
OCR artifacts in pts text

### ISSUE THREAD

**Issue by shelleyfrank** [suttacentral/sc-data#75]
pts.json
7550 word: nicchodeti
Towards the end of the paragraph, what you have is: 
`For sound change P. ch&lt;sk. kṣ cp. P chamā&lt;k ch churik etc.`
It should be:
`For sound change P. ch &gt; Sk. kṣ cp. P chamā &gt; kṣāra, chārikā &gt; kṣāra churikā &gt; kṣurikā etc.`

I have checked the entry in the pdf scan. This has to be an ocr error. The less-than signs are in face greater-than signs in the print.

**Comment by sujato** [comment]
Thanks. I have fixed it.
